package net.kasterma.paxos;

import java.util.function.Supplier;

/**
 * In order to generate disjoint sequences we use arithmetic sequences with
 * stepSize big enough so that we step over the indices generated by the others.
 *
 * I.e. if need three sequences can use
 *    GenerateProposalIdx(0, 3), GenerateProposalIdx(1, 3), and
 *    GenrateProposalIdx(2, 3).
 */
public class GenerateProposalIdx implements Supplier<Integer> {
    private int next;
    private final int stepSize;

    GenerateProposalIdx(final int next, final int stepSize) {
        this.next = next;
        this.stepSize = stepSize;
    }

    @Override
    final public Integer get() {
        int rv = next;
        next += stepSize;
        return rv;
    }
}
